services:
  # Service Web Django
  - type: web
    name: eventhub-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT"
    autoDeploy: yes
    
    # Variables d'environnement
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings.production
      - key: PYTHON_VERSION
        value: 3.11
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_NAME
        value: libredb
      - key: DATABASE_USER
        value: libre_user
      - key: DATABASE_HOST
        value: eventhub-db
      - key: DATABASE_PORT
        value: 5432
      - fromDatabase:
          name: eventhub-db
          property: connectionString
          key: DATABASE_PASSWORD
        
  # Service PostgreSQL
  - type: pserv
    name: eventhub-db
    env: postgres
    plan: free
    databases:
      - name: libredb
        user: libre_user
        
# Configuration du déploiement
version: "1"
